// Data + i18n dictionary for ODA al Vino 2026
const I18N = {
  es: {
    nav: { manifiesto: "Manifiesto", experiencia: "Experiencia", tickets: "Entradas", bodegas: "Bodegas", venue: "Venue", legado: "Legado", iguazu: "Iguazú", contacto: "Contacto" },
    cta: { buy: "Comprar entrada", waitlist: "Sumate a la lista", discover: "Descubrir", bePart: "Quiero ser bodega" },
    hero: {
      eyebrow: "10° Edición · Triple Frontera",
      titleA: "El vino nos",
      titleScript: "Reúne",
      titleB: "",
      subtitle: "Dos días para descubrir, brindar y recorrer Argentina a través de sus mejores etiquetas.",
      date: "4 Y 5 DE SEPTIEMBRE",
      year: "2026",
      place: "IGUAZÚ · ARGENTINA",
      scroll: "Deslizá para entrar",
    },
    manifesto: {
      eyebrow: "Manifiesto",
      line1: "Una",
      script: "Celebración",
      line2: "del vino argentino en el corazón de la Triple Frontera.",
      body: "ODA al Vino es el punto de encuentro donde el vino argentino se vive, se aprende y se comparte. Una celebración de la cultura, los sentidos y la comunidad que ya lleva diez años reuniendo a quienes aman lo que hay detrás de cada copa.",
      tags: "Degustación · Experiencias · Gastronomía · Comunidad",
    },
    scale: {
      eyebrow: "La escala de la celebración",
      stats: [
        { n: "+150", t: "Bodegas", s: "argentinas participando" },
        { n: "+700", t: "Etiquetas", s: "listas para descubrir" },
        { n: "+2.000", t: "Asistentes", s: "de tres países" },
        { n: "10°", t: "Edición", s: "desde 2015" },
      ],
    },
    experience: {
      eyebrow: "La Experiencia",
      titleA: "Viví el",
      script: "Vino",
      titleB: "de otra manera",
      items: [
        { n: "01", t: "Descubrí", d: "Recorré bodegas, probá nuevas etiquetas y dejate sorprender por proyectos boutique, orgánicos y clásicos." },
        { n: "02", t: "Conectá", d: "Conocé a enólogos, sommeliers y a quienes hacen el vino. Una comunidad que comparte historia, origen y paisaje." },
        { n: "03", t: "Disfrutá", d: "Gastronomía pensada como maridaje, pensada para acompañar cada momento y cada copa del recorrido." },
        { n: "04", t: "Aprendé", d: "Masterclasses, charlas y cataciones guiadas que transforman la forma de vivir el vino." },
      ],
    },
    tickets: {
      eyebrow: "✦ Lanzamiento Oficial · Cupos iniciales ✦",
      titleA: "Asegurá tu",
      script: "Lugar",
      titleB: "",
      sub: "Una única entrada. El precio cambia según el momento — mejor ahora que después.",
      includes: "Qué incluye",
      list: [
        "Acceso al evento los dos días (4 y 5 de septiembre)",
        "Copa de cristal personalizada OAV 2026",
        "Voucher de consumo en ODA y ODF por R$200",
        "Degustaciones sin cargo durante todo el recorrido",
        "Acceso a charlas y masterclasses del mundo del vino",
      ],
      lots: [
        { label: "Lote de lanzamiento", status: "Disponible ahora", r: "500", ars: "11.750", pyg: "4.250.000" },
        { label: "Próximo lote", status: "Hasta agotar stock", r: "540", ars: "12.690", pyg: "4.590.000" },
        { label: "Tercera etapa", status: "Julio 2026", r: "620", ars: "14.570", pyg: "5.270.000" },
        { label: "Último lote", status: "Final · puerta", r: "670", ars: "15.745", pyg: "5.695.000" },
      ],
      cta: "Comprar ahora",
      foot: "Sin intermediarios · Acceso garantizado · Pago seguro",
      urgency: "El precio aumenta en las próximas etapas",
    },
    bodegas: {
      eyebrow: "Los Protagonistas",
      titleA: "Más de 150",
      script: "Bodegas",
      titleB: "argentinas",
      sub: "De Mendoza a Salta, de La Rioja a la Patagonia. Clásicos, boutiques, proyectos orgánicos y de garaje conviven en un mismo recorrido.",
      regions: [
        { n: "Mendoza", pct: "64%", d: "Malbec, Cabernet Franc, Bonarda" },
        { n: "Salta", pct: "12%", d: "Torrontés, Malbec de altura" },
        { n: "Patagonia", pct: "9%", d: "Pinot Noir, Merlot, Sauvignon" },
        { n: "La Rioja", pct: "6%", d: "Torrontés Riojano, Bonarda" },
        { n: "San Juan", pct: "5%", d: "Syrah, Cabernet, Malbec" },
        { n: "Otras", pct: "4%", d: "Neuquén, Catamarca, Córdoba" },
      ],
      seeAll: "Ver todas las bodegas",
    },
    venue: {
      eyebrow: "El Lugar",
      titleA: "Iguassu",
      script: "Urban Mall",
      titleB: "",
      address: "Avenida República Argentina, 86 · Puerto Iguazú",
      sub: "Dos plantas, más de mil personas por día, 200 stands y stands de hasta dos barriles.",
      floors: [
        { name: "Planta Baja", cap: "445", desc: "Bodegas, degustación y entrada principal" },
        { name: "Primer Piso", cap: "650", desc: "Sala gourmet, charlas y masterclasses" },
      ],
      total: "1.095 personas de capacidad total",
    },
    legacy: {
      eyebrow: "La Historia",
      titleA: "Diez años",
      script: "Reuniendo",
      titleB: "amantes del vino",
      sub: "De una vinoteca a la feria de vinos argentinos más importante de la región trinacional.",
      timeline: [
        { y: "2015", t: "Nace ODA al Vino", d: "46 bodegas, primera edición en la vinoteca ODA." },
        { y: "2016", t: "Se duplica", d: "+60 bodegas y la gastronomía regional entra en escena." },
        { y: "2017", t: "3° edición", d: "Degustación exclusiva para hotelería y restaurantes." },
        { y: "2018", t: "Reconocimiento", d: "Se consolida como feria de referencia del vino argentino." },
        { y: "2019", t: "5° edición", d: "+85 bodegas, +1.500 asistentes. Nace la premisa Sentir · Conocer · Deleitar." },
        { y: "2022", t: "Regreso", d: "+104 bodegas, +600 etiquetas tras la pausa pandémica." },
        { y: "2023", t: "Sustentable", d: "+116 bodegas. 1° evento sustentable certificado de Puerto Iguazú." },
        { y: "2024", t: "Récord", d: "+125 bodegas, +700 etiquetas, +2.000 asistentes, destilerías boutique." },
        { y: "2025", t: "9° edición", d: "La feria consolida su posición regional como referente." },
        { y: "2026", t: "10° Edición", d: "Celebramos una década. El evento más esperado del calendario enológico latinoamericano.", active: true },
      ],
    },
    testimonials: {
      eyebrow: "Lo que dicen",
      titleA: "La comunidad",
      script: "Habla",
      titleB: "",
      quotes: [
        { q: "Realmente pocas personas logran aportar tanto como Lilian. Cada año el evento se supera y ya forma parte de la ciudad. Termina uno y ya estamos esperando el próximo.", a: "Carlos Chain", r: "Wine tester" },
        { q: "Un evento delicioso, con muchas etiquetas que no conocía. Una maravilla. Lo recomiendo con total tranquilidad.", a: "Janine Regina", r: "Sommelière" },
        { q: "Ansiosa por participar de las salas de degustación. Una experiencia que cada año se refina y sorprende.", a: "Simone Schiebelbein de Campos", r: "Enófila" },
        { q: "Fue maravilloso. Felicitaciones a todos. ¡Hasta el año que viene!", a: "Daniela Veloso", r: "Amante del vino" },
      ],
    },
    iguazu: {
      eyebrow: "Más allá del evento",
      titleA: "Tres países,",
      script: "una Copa",
      titleB: "",
      sub: "Desayunar en Argentina, almorzar en Brasil, cenar en Paraguay. Iguazú es el único lugar donde la Triple Frontera se vive en un mismo día.",
      items: [
        { t: "Cataratas", d: "Una de las 7 maravillas naturales del mundo, a 20 minutos del venue.", img: "assets/cataratas.png" },
        { t: "Triple Frontera", d: "El hito que marca el encuentro de Argentina, Brasil y Paraguay.", img: "assets/noria.png" },
        { t: "Gasto promedio", d: "R$3.500 / USD 650 por wine lover durante el fin de semana.", stat: true },
      ],
    },
    b2b: {
      eyebrow: "Para Bodegas",
      titleA: "Ser parte de",
      script: "ODA",
      titleB: "al Vino",
      sub: "Una oportunidad única para conectar directamente con consumidores calificados, fortalecer posicionamiento y crear alianzas estratégicas.",
      stand: "Stands de 2 barriles con 2 metros de frente",
      lots: [
        { venc: "1° Vencimiento", date: "hasta 31/05/2026", price: "$650.000" },
        { venc: "2° Vencimiento", date: "hasta 30/06/2026", price: "$750.000" },
        { venc: "3° Vencimiento", date: "hasta 31/07/2026", price: "$850.000" },
      ],
      note: "+ IVA · Reservas con pago anticipado del 50% · Canje hasta 50% en mercadería para bodegas incorporadas.",
      cta: "Reservar stand",
      contact: "gerencia@odavinoteca.com.ar · +54 9 3757 571591",
    },
    final: {
      titleA: "El vino",
      script: "Nos reúne",
      titleB: "",
      date: "4 · 5 SEPTIEMBRE 2026",
      place: "IGUASSU URBAN MALL · PUERTO IGUAZÚ",
      cta: "Asegurá tu entrada",
    },
    footer: {
      tagline: "La feria de vinos argentinos más importante de la Triple Frontera.",
      links1: ["Manifiesto", "Experiencia", "Entradas", "Bodegas", "Venue", "Historia"],
      links2: ["Prensa", "B2B · Stands", "Sponsors", "Preguntas frecuentes"],
      social: ["Instagram", "Facebook", "YouTube"],
      legal: "© ODA al Vino 2026 · Organizado por ODA Vinoteca · 1° evento sostenible certificado de Puerto Iguazú",
    },
  },
  pt: {
    nav: { manifiesto: "Manifesto", experiencia: "Experiência", tickets: "Ingressos", bodegas: "Vinícolas", venue: "Local", legado: "Legado", iguazu: "Foz", contacto: "Contato" },
    cta: { buy: "Comprar ingresso", waitlist: "Entre na lista", discover: "Descobrir", bePart: "Quero expor" },
    hero: {
      eyebrow: "10ª Edição · Tríplice Fronteira",
      titleA: "O vinho nos",
      titleScript: "Reúne",
      titleB: "",
      subtitle: "Dois dias para descobrir, brindar e percorrer a Argentina através dos seus melhores rótulos.",
      date: "4 E 5 DE SETEMBRO",
      year: "2026",
      place: "FOZ DO IGUAÇU · ARGENTINA",
      scroll: "Role para entrar",
    },
    manifesto: {
      eyebrow: "Manifesto",
      line1: "Uma",
      script: "Celebração",
      line2: "do vinho argentino no coração da Tríplice Fronteira.",
      body: "ODA al Vino é o ponto de encontro onde o vinho argentino se vive, se aprende e se compartilha. Uma celebração da cultura, dos sentidos e da comunidade que já reúne há dez anos quem ama o que existe por trás de cada taça.",
      tags: "Degustação · Experiências · Gastronomia · Comunidade",
    },
    scale: {
      eyebrow: "A escala da celebração",
      stats: [
        { n: "+150", t: "Vinícolas", s: "argentinas participando" },
        { n: "+700", t: "Rótulos", s: "prontos para descobrir" },
        { n: "+2.000", t: "Visitantes", s: "de três países" },
        { n: "10ª", t: "Edição", s: "desde 2015" },
      ],
    },
    experience: {
      eyebrow: "A Experiência",
      titleA: "Viva o",
      script: "Vinho",
      titleB: "de outra forma",
      items: [
        { n: "01", t: "Descubra", d: "Percorra vinícolas, prove novos rótulos e deixe-se surpreender por projetos boutique, orgânicos e clássicos." },
        { n: "02", t: "Conecte", d: "Conheça enólogos, sommeliers e quem faz o vinho. Uma comunidade que compartilha história, origem e paisagem." },
        { n: "03", t: "Aproveite", d: "Gastronomia pensada como harmonização, feita para acompanhar cada momento e cada taça do percurso." },
        { n: "04", t: "Aprenda", d: "Masterclasses, palestras e degustações guiadas que transformam a forma de viver o vinho." },
      ],
    },
    tickets: {
      eyebrow: "✦ Lançamento Oficial · Vagas iniciais ✦",
      titleA: "Garanta seu",
      script: "Lugar",
      titleB: "",
      sub: "Um único ingresso. O preço muda conforme o momento — melhor agora do que depois.",
      includes: "O que inclui",
      list: [
        "Acesso ao evento nos dois dias (4 e 5 de setembro)",
        "Taça de cristal personalizada OAV 2026",
        "Voucher de consumo na ODA e ODF de R$200",
        "Degustações gratuitas durante todo o percurso",
        "Acesso a palestras e masterclasses do mundo do vinho",
      ],
      lots: [
        { label: "Lote de lançamento", status: "Disponível agora", r: "500", ars: "11.750", pyg: "4.250.000" },
        { label: "Próximo lote", status: "Até esgotar", r: "540", ars: "12.690", pyg: "4.590.000" },
        { label: "Terceira etapa", status: "Julho 2026", r: "620", ars: "14.570", pyg: "5.270.000" },
        { label: "Último lote", status: "Final · na porta", r: "670", ars: "15.745", pyg: "5.695.000" },
      ],
      cta: "Comprar agora",
      foot: "Sem intermediários · Acesso garantido · Pagamento seguro",
      urgency: "O preço aumenta nas próximas etapas",
    },
    bodegas: {
      eyebrow: "Os Protagonistas",
      titleA: "Mais de 150",
      script: "Vinícolas",
      titleB: "argentinas",
      sub: "De Mendoza a Salta, de La Rioja à Patagônia. Clássicas, boutiques, projetos orgânicos e de garagem convivem num mesmo percurso.",
      regions: [
        { n: "Mendoza", pct: "64%", d: "Malbec, Cabernet Franc, Bonarda" },
        { n: "Salta", pct: "12%", d: "Torrontés, Malbec de altitude" },
        { n: "Patagônia", pct: "9%", d: "Pinot Noir, Merlot, Sauvignon" },
        { n: "La Rioja", pct: "6%", d: "Torrontés Riojano, Bonarda" },
        { n: "San Juan", pct: "5%", d: "Syrah, Cabernet, Malbec" },
        { n: "Outras", pct: "4%", d: "Neuquén, Catamarca, Córdoba" },
      ],
      seeAll: "Ver todas as vinícolas",
    },
    venue: {
      eyebrow: "O Local",
      titleA: "Iguassu",
      script: "Urban Mall",
      titleB: "",
      address: "Avenida República Argentina, 86 · Puerto Iguazú",
      sub: "Dois andares, mais de mil pessoas por dia, 200 stands e stands de até dois barris.",
      floors: [
        { name: "Térreo", cap: "445", desc: "Vinícolas, degustação e entrada principal" },
        { name: "Primeiro Andar", cap: "650", desc: "Sala gourmet, palestras e masterclasses" },
      ],
      total: "1.095 pessoas de capacidade total",
    },
    legacy: {
      eyebrow: "A História",
      titleA: "Dez anos",
      script: "Reunindo",
      titleB: "amantes do vinho",
      sub: "De uma vinoteca à feira de vinhos argentinos mais importante da região trinacional.",
      timeline: [
        { y: "2015", t: "Nasce ODA al Vino", d: "46 vinícolas, primeira edição na vinoteca ODA." },
        { y: "2016", t: "Dobra de tamanho", d: "+60 vinícolas e a gastronomia regional entra em cena." },
        { y: "2017", t: "3ª edição", d: "Degustação exclusiva para hotelaria e restaurantes." },
        { y: "2018", t: "Reconhecimento", d: "Consolida-se como feira de referência do vinho argentino." },
        { y: "2019", t: "5ª edição", d: "+85 vinícolas, +1.500 visitantes. Nasce a premissa Sentir · Conhecer · Deleitar." },
        { y: "2022", t: "Regresso", d: "+104 vinícolas, +600 rótulos após a pausa pandêmica." },
        { y: "2023", t: "Sustentável", d: "+116 vinícolas. 1º evento sustentável certificado de Puerto Iguazú." },
        { y: "2024", t: "Recorde", d: "+125 vinícolas, +700 rótulos, +2.000 visitantes, destilarias boutique." },
        { y: "2025", t: "9ª edição", d: "A feira consolida sua posição regional como referência." },
        { y: "2026", t: "10ª Edição", d: "Celebramos uma década. O evento mais esperado do calendário enológico latino-americano.", active: true },
      ],
    },
    testimonials: {
      eyebrow: "O que dizem",
      titleA: "A comunidade",
      script: "Fala",
      titleB: "",
      quotes: [
        { q: "Poucas pessoas conseguem entregar tanto quanto a Lilian. Cada ano o evento se supera e já faz parte da cidade. Termina um e já estamos esperando o próximo.", a: "Carlos Chain", r: "Wine tester" },
        { q: "Um evento delicioso, com muitos rótulos que eu não conhecia. Uma maravilha. Recomendo com total tranquilidade.", a: "Janine Regina", r: "Sommelière" },
        { q: "Ansiosa para participar das salas de degustação. Uma experiência que a cada ano se refina e surpreende.", a: "Simone Schiebelbein de Campos", r: "Enófila" },
        { q: "Foi maravilhoso. Parabéns a todos. Até o ano que vem!", a: "Daniela Veloso", r: "Amante do vinho" },
      ],
    },
    iguazu: {
      eyebrow: "Além do evento",
      titleA: "Três países,",
      script: "uma Taça",
      titleB: "",
      sub: "Café da manhã na Argentina, almoço no Brasil, jantar no Paraguai. Foz é o único lugar onde a Tríplice Fronteira se vive no mesmo dia.",
      items: [
        { t: "Cataratas", d: "Uma das 7 maravilhas naturais do mundo, a 20 minutos do local.", img: "assets/cataratas.png" },
        { t: "Tríplice Fronteira", d: "O marco do encontro entre Argentina, Brasil e Paraguai.", img: "assets/noria.png" },
        { t: "Gasto médio", d: "R$3.500 / USD 650 por wine lover no fim de semana.", stat: true },
      ],
    },
    b2b: {
      eyebrow: "Para Vinícolas",
      titleA: "Fazer parte do",
      script: "ODA",
      titleB: "al Vino",
      sub: "Uma oportunidade única para conectar-se diretamente com consumidores qualificados, fortalecer posicionamento e criar alianças estratégicas.",
      stand: "Stands de 2 barris com 2 metros de frente",
      lots: [
        { venc: "1° Vencimento", date: "até 31/05/2026", price: "$650.000" },
        { venc: "2° Vencimento", date: "até 30/06/2026", price: "$750.000" },
        { venc: "3° Vencimento", date: "até 31/07/2026", price: "$850.000" },
      ],
      note: "+ IVA · Reservas com pagamento antecipado de 50% · Permuta de até 50% em mercadoria para vinícolas incorporadas.",
      cta: "Reservar stand",
      contact: "gerencia@odavinoteca.com.ar · +54 9 3757 571591",
    },
    final: {
      titleA: "O vinho",
      script: "Nos reúne",
      titleB: "",
      date: "4 · 5 SETEMBRO 2026",
      place: "IGUASSU URBAN MALL · PUERTO IGUAZÚ",
      cta: "Garanta seu ingresso",
    },
    footer: {
      tagline: "A feira de vinhos argentinos mais importante da Tríplice Fronteira.",
      links1: ["Manifesto", "Experiência", "Ingressos", "Vinícolas", "Local", "História"],
      links2: ["Imprensa", "B2B · Stands", "Patrocinadores", "Perguntas frequentes"],
      social: ["Instagram", "Facebook", "YouTube"],
      legal: "© ODA al Vino 2026 · Organizado por ODA Vinoteca · 1° evento sustentável certificado de Puerto Iguazú",
    },
  },
};

// 150 mock bodegas for the marquee grid
const BODEGAS = [
  "Catena Zapata","Trapiche","Zuccardi","Rutini","Norton","Luigi Bosca","Alta Vista","Bodega Chandon","Terrazas de los Andes","Achaval Ferrer",
  "El Enemigo","Riglos","Susana Balbo","Salentein","Bianchi","Humberto Canale","Del Fin del Mundo","Finca La Anita","Mendel","Lagarde",
  "Finca Decero","Pulenta Estate","Fabre Montmayou","Bemberg Estate","Kaiken","Masi Tupungato","Colomé","El Esteco","Amalaya","Yacochuya",
  "Piattelli","Tahuan","Alfredo Roca","Familia Schroeder","Bodega del Desierto","Viñas del Nant y Fall","Otronia","Bodega Malma","Noemia","Chacra",
  "Pascual Toso","Graffigna","Finca Las Moras","Callia","Xumek","Cavas de Zonda","El Portillo","Tomero","Barda","Escorihuela Gascón",
  "Séptima","Melipal","Ruca Malen","Tapiz","Dominio del Plata","Clos de los Siete","Vistalba","Terroir Cristal","Argento","Finca Sophenia",
  "Andeluna","Gimenez Riili","Navarro Correas","Renacer","Bressia","Casarena","Altos las Hormigas","Alpamanta","Matervini","Passionate Wine",
  "El Nacional","Luca","Tikal","DiamAndes","Monteviejo","Flechas de los Andes","Rolland","Achaval","Durigutti","Per Se",
  "Finca Beth","Riccitelli","Zaha","Altos del Plata","Los Haroldos","La Rural","Bodega Nieto Senetiner","Bianchi Famiglia","López","Valle de la Puerta",
  "La Azul","Finca Flichman","Otaviano","Corbeau","Gouguenheim","Atamisque","Chandon Terrazas","Finca Adalgisa","Finca El Origen","Familia Zuccardi",
  "Uxmal","Cuarto Dominio","Cepas de Altura","Vinecol","Santa Julia","Septima","Tikal Patagonia","Moet Hennessy","Bodega La Rosa","Finca Eugenio Bustos",
  "Bodega Argento","Anko","Tapaus","Colonia Las Liebres","Etchart","Tacuil","Porvenir","Raco","Calchaquí","Vasija Secreta",
  "Puri","Huarpe","Bodega Ruca","Cielo de Tupungato","Finca Mate","Otoño Fresh","Las Perdices","Los Arboles","Dante Robino","Santa Ana",
  "Bodegas Bianchi","Ver Sacrum","Tierra de Alma","Luigi Bosca Deseado","Susana Balbo Crios","Benegas","Baudron","Budeguer","Aluminé","Mauricio Lorca",
  "Familia Mayol","Buena Onda","Cruzat","Rosell Boher","Alta Yary","Costa&Pampa","Sophenia Altosur","Finca Alzada","Piedra Negra","Nieto Senetiner Don Nicanor",
  "Winston","Zorzal","Ojo de Agua","Trivento","Escorihuela","Fincas del Lago","Bodega Lavaque","La Constancia","Huarpe","Altocedro",
];

// Gallery images for experience + legacy
const GALLERY = {
  oav23: ["assets/gallery/oav23-1.webp","assets/gallery/oav23-2.webp","assets/gallery/oav23-3.webp","assets/gallery/oav23-4.webp"],
  oav24: ["assets/gallery/oav24-1.webp","assets/gallery/oav24-2.webp","assets/gallery/oav24-3.webp","assets/gallery/oav24-4.webp","assets/gallery/oav24-5.webp","assets/gallery/oav24-6.webp"],
  oav25: ["assets/gallery/oav25-1.webp","assets/gallery/oav25-2.webp","assets/gallery/oav25-3.webp","assets/gallery/oav25-4.webp","assets/gallery/oav25-5.webp","assets/gallery/oav25-6.webp"],
};

Object.assign(window, { I18N, BODEGAS, GALLERY });
